application: sandysback
version: 1
runtime: python
api_version: 1

handlers:
- url: /fromail
  script: main.py
- url: /bare
  script: main.py
- url: /test.*
  script: gaeunit.py

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /(.*)\.html
  static_files: \1.html
  upload: (.*).html

- url: .*
  script: main.py
  # login: required

